language: node_js
branches:
  only:
    - master
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  fqdn: www.matiasbn.com
  on:
    branch: master
