language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  github_token: $github_token
  local_dir: build
  fqdn: www.matiasbn.com
  keep_history: true
  on:
    branch: master
